version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html
      - ./admin/build:/usr/share/nginx/html/admin
    depends_on:
      - server
      - admin
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/healthy-food
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRE=24h
    ports:
      - "5000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "5001:3000"
    volumes:
      - ./admin:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  mongodb:
    image: mongo:6.0-focal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
